### ISSUE TITLE
inconsistency?

### ISSUE THREAD

**Issue by pro465** [catseye/Eqthy#4]
in the propositional algebra file, you have this axiom as modus ponens: 
[https://github.com/catseye/Eqthy/blob/3a7bb427a58bed740605e37445817f0f54485c9f/eg/propositional-algebra.eqthy.md?plain=1#L31](https://github.com/catseye/Eqthy/blob/3a7bb427a58bed740605e37445817f0f54485c9f/eg/propositional-algebra.eqthy.md?plain=1#L31)

i believe that leads to inconsistency, as the equal sign means that we can deduce the "converse" too, which means we can deduce `th(P, th(impl(P, Q), e))` from `th(Q, e)` **for all `P`**, which is bad

**Comment by pro465** [comment]
@cpressey i don't know if being in an organization means you get notifications for that org activity, so i just wanted to make sure.

**Comment by pro465** [comment]
here's an example of deriving `not(Q)` from `Q`, thus resulting in a contradiction:

    axiom (#MP) th(P, th(impl(P, Q), e)) = th(Q, e) 
    theorem (contradiction) 
        th(Q, e) = th(not(Q), th(impl(not(Q), Q), e))
    proof
        th(Q, e) = th(Q, e)
        th(Q, e) = th(P, th(impl(P, Q), e))           [by #MP]
        th(Q, e) = th(not(Q), th(impl(not(Q), Q), e)) [by substitution of not(Q) into P]
    qed

**Comment by cpressey** [comment]
Hi Proloy - thanks for your interest.

Working with a logic as an algebra is a little unusual and it's entirely possible there's a mistake somewhere, but I don't think I see an actual inconsistency here.

In this development, `th(...)` represents a set of theorems.  They're represented concretely as a list, but we don't care about ordering or duplicates.

The statement `th(Q, e) = th(not(Q), th(impl(not(Q), Q), e))` is saying: "For any Q, the set of theorems {Q} is equivalent to the set of theorems {¬Q, ¬Q → Q}."

So, yes, starting with Q, you can derive ¬Q, but *only* if you *also* derive ¬Q → Q.

This seems entirely fair to me?  It does seem to indicate that for any set of theorems you might find interesting, there are many equivalent sets that are full of junk and thus probably uninteresting.  But that doesn't seem to lead to any actual problems that I can see.

On the other hand, if we had the statement `th(Q, e) = th(not(Q), e)`, that would be saying "For any Q, the set of theorems {Q} is equivalent to the set of theorems {¬Q}", and I would agree that that represents an inconsistency.  And if you could derive that statement from the axioms in `propositional-algebra.eqthy.md`, I would agree that would definitely indicate a problem somewhere.

**Comment by pro465** [comment]
well, what do you think of this?

    axiom (#A1) th(X, e) = th(X, th(impl(P, impl(Q, P)), e))
    axiom (#A3) th(X, e) = th(X, th(impl(not(not(P)), P), e))
    axiom (#MP) th(P, th(impl(P, Q), e)) = th(Q, e) 
    
    theorem (triviality) 
        th(X, e) = th(X, th(P, e))
    proof
        th(Q, e) = th(Q, e)
        th(Q, e) = th(P, th(impl(P, Q), e))                       [by #MP]
        th(impl(Q, P), e) = th(P, th(impl(P, impl(Q, P)), e))     [by substitution of impl(Q, P) into Q]

        th(impl(Q, P), e) = th(P, e)                              [by #A1]

        th(impl(not(not(P)), P), e) = th(P, e)                    [by substitution of not(not(P)) into Q]        
        th(X, th(impl(not(not(P)), P), e)) = th(X, th(P, e))      [by congruence of C and th(X, C)]
        th(X, e) = th(X, th(P, e))                                [by #A3]
    qed

**Comment by cpressey** [comment]
OK -- what if we change `#MP` to

    axiom (#MP) th(X, th(P, th(impl(P, Q), e))) = th(X, th(Q, th(P, th(impl(P, Q), e))))

?

I'm honestly not sure at the moment if it addresses the problem you're describing (probably it does), but now that you've made me take a hard look at these, it's a hole that clearly needs to be plugged.  After giving A1-A3, Mack and Barnes say that their one rule of inference is modus ponens, but they don't define it very formally, they just say "from _p_ and _p_ → _q_, deduce _q_." ... and I transliterated that far too literally here.  Modus ponens isn't justified in erasing anything from the theory set.

I'd also propose to add a third structural axiom

    axiom (#th-idemp)  th(X, th(X, Y)) = th(X, Y)

to reflect the fact that `th(...)` is supposed to represent a set, so we don't care about duplicates.

**Comment by pro465** [comment]
As far as I can see, the revised MP does seem to be fine. In fact, it's exactly what I had in mind. The reason that I think it's fine compared to the old one is as follows:

`A = B` means `A := B` and `B := A`, where `:=` is `=` without the symmetry axiom (basically nnoq's `:=` operator). in the old MP, one of those meant that if you had a theorem (or true proposition) `Q`, you can rewrite that to `P and P => Q` and it would still be valid (false, as `P` may not be a theorem (or true proposition)).  

Whereas in the new one, the two axioms are modus ponens and a restricted conjunction elimination (both valid). So, I think the new one is valid.

**Comment by pro465** [comment]
also, regarding your third proposed axiom: I think it's fine? I don't see any problem with it.

**Comment by pro465** [comment]
Regarding the informal use of deduce: I think that if a text says `from A, deduce B` it almost always implicitly means they add B to the set of true propositions, not actually replace A by B. proofs in propositional logic, from what I've seen, are able to deduce from a previous proposition multiple times, which would mean either:
    1. They duplicated the propositions before deducing from them.
    2. They did not replace the propositions with their conclusions, and instead added to the set of true propositions.   

For me, the latter seems more natural. And even if the former was true, it does not seem to work well under equational logic, as evidenced by the current implementation of it in Eqthy.  

the only problem I see with the latter is that by the end of a proof, you'd be left with your intended theorem, along with a long list of intermediate theorems/lemmas used to reach the theorem. You would need a conjunction elimination axiom to remove the "unneeded" theorems. But a correct conjunction elimination axiom (without it leading to triviality) seems tricky to define in Eqthy.

**Comment by pro465** [comment]
Hello, so I was reading the wikipedia article on propositional logic and chanced upon this:
https://en.wikipedia.org/wiki/Propositional_calculus#Equivalence_to_equational_logics
what do you think of it?

I think it proves that a conjunction elimination axiom is not even needed in equational logics, proof:
1. given a set of theorems $A$ and a theorem $B$ that follows from $A$, we can write $A \vdash B$ as $A = A \cup \set{B}$.
2. we can now remove $B$ from the set of theorems by simply applying the equation in reverse.
3. since all the axioms (well, the revised ones, anyway) are of this form, we can thus remove any theorems that were added by applying the axioms, by applying in reverse the axiom(s) used to add it.
4. since all theorems added to the set $A$ are added only by applying a finite sequence of axioms, all theorems in $A$ can be removed.

**Comment by pro465** [comment]
@cpressey did you not get the notifications, or are you just busy and planning to think about this later?

if it's the latter, I might be able to open a PR and fix this myself (if you allow me to...)

**Comment by cpressey** [comment]
> @cpressey did you not get the notifications, or are you just busy and planning to think about this later?

Generally speaking I'm busy.  Please don't expect notifying me to result in an immediate response

**Comment by pro465** [comment]
> OK -- what if we change `#MP` to
> 
> ```
> axiom (#MP) th(X, th(P, th(impl(P, Q), e))) = th(X, th(Q, th(P, th(impl(P, Q), e))))
> ```
> 
> ?

I think it could be simplified a bit to:
```
axiom (#MP) th(P, th(impl(P, Q), e)) = th(Q, th(P, th(impl(P, Q), e)))
```

**Comment by cpressey** [comment]
I've used the new MP that I proposed in `propositional-algebra.eqthy.md` to at least stop it from being based on an inconsistent axiom system.  I also updated the proof, and, just as you observe:

> the only problem I see with the latter is that by the end of a proof, you'd be left with your intended theorem, along with a long list of intermediate theorems/lemmas used to reach the theorem.

I agree that it's unwieldy.  But then, I knew going in that Eqthy would be annoying to work with!  So I'm not _too_ fussed about this.  You do have to look at the set of theorems and see that it contains the proposition you wanted to prove; but, the set does contain the proposition.

So it shows that it is at least possible.  But sure, it would be nice if it looked more like a direct proof.

I haven't given much thought to elimination as of yet.  What we'd want to show is that the set on the RHS has {`impl(P, P)`} as a subset; so maybe some kind of subset operation could be defined; but I don't know yet.  I'll see how much time I have to think about it.

Regarding

> `axiom (#MP) th(P, th(impl(P, Q), e)) = th(Q, th(P, th(impl(P, Q), e)))`

, yes, this simplification probably continues to suffice, on the principle that any axiom like `th(X, Y) = th(X, Z)` can be simplified to `Y = Z` because Eqthy can apply `Y = Z` anywhere inside a term.

I don't see why all of A1, A2, and A3 couldn't be simplified this way too.

I don't remember exactly why I put all the axioms in the `th(X, ...) = th(X, ...)` form; maybe I was initially thinking axioms would only be applied in an outermost fashion; or something else.

**Comment by pro465** [comment]
For now, I fixed the intermediate theorems. However, the proof got large and clunky. I still don't know if there is a more direct way to remove theorems other than just applying the axioms/theorems that led to them in reverse.  

I suppose the proof could be better documented, but I am not great at documenting things.

**Comment by pro465** [comment]
also, if you change the axioms to add theorems anywhere instead of just at the end, it would require less steps in general to prove a given theorem, due to not having to move theorems around.

for example:
```
axiom (#A1) X = th(impl(P, impl(Q, P)), X)
```
of course it means you could also derive nonsensical theorems like `1 = th(impl(P, impl(Q, P)), 1)`, because it's untyped, but that has always been a problem, so I don't believe it suddenly matters now.

**Comment by cpressey** [comment]
> For now, I fixed the intermediate theorems. However, the proof got large and clunky. I still don't know if there is a more direct way to remove theorems other than just applying the axioms/theorems that led to them in reverse.

I was actually a bit surprised to see that it was as straightforward as applying them in reverse.  But in retrospect it also seems obvious.  So I'm a bit disappointed in myself for being surprised.  Well, I haven't really had my head in this space lately, and it doesn't come very naturally to me anyway.

This is fine though, I don't care that it's clunky.  Thanks for the contribution, I'll merge it in soon.

> also, if you change the axioms to add theorems anywhere instead of just at the end, it would require less steps in general to prove a given theorem, due to not having to move theorems around.

Yes, it's just a set (morally speaking) so there really needn't be a distinction about "where" the theorems are in it.  This is a major factor in how tedious Eqthy proofs are to write.  As a sort of longer-term goalI'd like to implement AC-unification in Eqthy, which would eliminate a lot of the "just moving things around" steps.  I have an idea which might lead to a simple implementation of it that I'd like to try (when I can find the time, which might not be anytime soon).

**Comment by pro465** [comment]
> [..] So I'm a bit disappointed in myself for being surprised.

I don't blame you, and I don't think you should too. I think we were so used to thinking of the axioms as only being supposed to be applied "forward" that we forgot that equality also means we can apply it in reverse too. I think the only reason I was able to "find" (more like remember) this is because I had thought of the implications of commutativity for equality before, when trying to prove the inconsistency of the initial axiomatization that led to this issue. Basically, I had more time to think of it than you.

> As a sort of longer-term goalI'd like to implement AC-unification in Eqthy, [..]

I would be very interested to see that kind of development. In the meantime, I'll try to read more about that (since it sounds like a deep rabbit hole).
